// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEM3-w6MCcdNXCtXDy5m3Bllvyt5KuaY',
    appId: '1:799835917197:web:f2454a5af031ccdd1c0bc4',
    messagingSenderId: '799835917197',
    projectId: 'geonix-wrench',
    authDomain: 'geonix-wrench.firebaseapp.com',
    storageBucket: 'geonix-wrench.firebasestorage.app',
    measurementId: 'G-2YPGFFWF3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE13Mvi3t64SaeBj1MIUe60-AuuBNWd0Q',
    appId: '1:799835917197:android:5f4ba4612ff29a5a1c0bc4',
    messagingSenderId: '799835917197',
    projectId: 'geonix-wrench',
    storageBucket: 'geonix-wrench.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPsjrAHYyFOJGZ_ngXk_sl9ISkan3wUo0',
    appId: '1:799835917197:ios:20492bce624588881c0bc4',
    messagingSenderId: '799835917197',
    projectId: 'geonix-wrench',
    storageBucket: 'geonix-wrench.firebasestorage.app',
    iosClientId: '799835917197-f8r4lha02o49ep8pfdef7jlgam4mgc8a.apps.googleusercontent.com',
    iosBundleId: 'com.geonixsoftware.wrench',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPsjrAHYyFOJGZ_ngXk_sl9ISkan3wUo0',
    appId: '1:799835917197:ios:20492bce624588881c0bc4',
    messagingSenderId: '799835917197',
    projectId: 'geonix-wrench',
    storageBucket: 'geonix-wrench.firebasestorage.app',
    iosClientId: '799835917197-f8r4lha02o49ep8pfdef7jlgam4mgc8a.apps.googleusercontent.com',
    iosBundleId: 'com.geonixsoftware.wrench',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLEM3-w6MCcdNXCtXDy5m3Bllvyt5KuaY',
    appId: '1:799835917197:web:01f712b64dbbd5c11c0bc4',
    messagingSenderId: '799835917197',
    projectId: 'geonix-wrench',
    authDomain: 'geonix-wrench.firebaseapp.com',
    storageBucket: 'geonix-wrench.firebasestorage.app',
    measurementId: 'G-4N5S1PCP0M',
  );
}
